version: '3.8'

services:
  ebpf-agent:
    build:
      context: ../..
      dockerfile: deploy/docker/ebpf-agent.Dockerfile
    container_name: netaiguard-ebpf-agent
    network_mode: host  # Необхідно для роботи eBPF
    privileged: true    # Необхідно для доступу до мережевих інтерфейсів
    volumes:
      - /sys/fs/bpf:/sys/fs/bpf
    command: [
      "--interface", "eth0",
      "--rate-limit", "100",
      "--ai-server", "http://localhost:5000",
      "--listen", ":8080"
    ]
    restart: unless-stopped

  ai-server:
    build:
      context: ../..
      dockerfile: deploy/docker/ai-server.Dockerfile
    container_name: netaiguard-ai-server
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - HOST=0.0.0.0
    restart: unless-stopped

  api-server:
    build:
      context: ../..
      dockerfile: deploy/docker/api-server.Dockerfile
    container_name: netaiguard-api-server
    ports:
      - "8081:8081"
    command: [
      "--ebpf-agent", "http://localhost:8080",
      "--ai-server", "http://localhost:5000",
      "--listen", ":8081"
    ]
    depends_on:
      - ebpf-agent
      - ai-server
    restart: unless-stopped

  web-ui:
    build:
      context: ../..
      dockerfile: deploy/docker/web-ui.Dockerfile
    container_name: netaiguard-web-ui
    ports:
      - "8082:8082"
    command: [
      "--static", "pkg/web",
      "--listen", ":8082"
    ]
    restart: unless-stopped